 
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push User Service image
        run: |
          docker build -t yourusername/user_service ./user_service
          docker push yourusername/user_service

      - name: Build and push Product Service image
        run: |
          docker build -t yourusername/product_service ./product_service
          docker push yourusername/product_service

      - name: Build and push Order Service image
        run: |
          docker build -t yourusername/order_service ./order_service
          docker push yourusername/order_service
